name: Publish

on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish:
    uses: jenly1314/actions/.github/workflows/reusable-publish.yml@v1
    with:
      java-version-file: '.github/workflows/.java-version'
    secrets:
      maven-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      gpg-secret-key: ${{ secrets.GPG_SECRET_KEY }}
      gpg-secret-passphrase: ${{ secrets.GPG_SECRET_PASSPHRASE }}
